# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end


Vinyl.create(album_name: "Lust For Life", artist_name: "Lana Del Rey")
Vinyl.create(album_name: "Ultraviolence", artist_name: "Lana Del Rey")
Vinyl.create(album_name: "Norman Fucking Rockwell", artist_name: "Lana Del Rey")
Vinyl.create(album_name: "Born to Die", artist_name: "Lana Del Rey")
Vinyl.create(album_name: "Die Lit", artist_name: "Playboi Carti")
Vinyl.create(album_name: "Playboi Carti", artist_name: "Playboi Carti")
Vinyl.create(album_name: "Whole lotta Red", artist_name: "Playboi Carti")
Vinyl.create(album_name:"Testing", artist_name:"A$AP Rocky")
Vinyl.create(album_name:"At Long Last A$ap", artist_name:"A$AP Rocky")
Vinyl.create(album_name:"Long Live A$ap", artist_name:"A$AP Rocky")
Vinyl.create(album_name:"Blond", artist_name:"Frank Ocean")
Vinyl.create(album_name:"Channel Orange", artist_name:"Frank Ocean")
Vinyl.create(album_name:"Nostalgia Ultra", artist_name:"Frank Ocean")
Vinyl.create(album_name:"OK Computer", artist_name:"Radiohead")
Vinyl.create(album_name:"Pablo Honey", artist_name:"Radiohead")
Vinyl.create(album_name:"Electric Ladyland", artist_name:"Jimi Hendrix")
Vinyl.create(album_name:"Treasure", artist_name:"Cocteau Twins")
Vinyl.create(album_name:"Folklore", artist_name:"Taylor Swift")
Vinyl.create(album_name:"Imperial", artist_name:"Denzel Curry")
Vinyl.create(album_name:"Ta1300", artist_name:"Denzel Curry")
Vinyl.create(album_name:"Unlocked", artist_name:"Denzel Curry")
Vinyl.create(album_name:"Rodeo", artist_name:"Travis Scott")
Vinyl.create(album_name:"Birds in the Trap Sing Mcknight", artist_name:"Travis Scott")
Vinyl.create(album_name:"Astroworld", artist_name:"Travis Scott")
Vinyl.create(album_name:"Around the Fur", artist_name:"Deftones")
Vinyl.create(album_name:"White Pony", artist_name:"Deftones")
Vinyl.create(album_name:"Diamond Eyes", artist_name:"Deftones")
Vinyl.create(album_name:"Saturday Night Wrist", artist_name:"Deftones")
Vinyl.create(album_name:"Flowerboy", artist_name:"Tyler, the Creator")
Vinyl.create(album_name:"Starboy", artist_name:"The Weeknd")
Vinyl.create(album_name:"Dawn FM", artist_name:"The Weeknd")
Vinyl.create(album_name:"Abyss", artist_name:"Pastel Ghost")
Vinyl.create(album_name:"Ethereality", artist_name:"Pastel Ghost")
Vinyl.create(album_name:"Hateful of hollow", artist_name:"The Smiths")
Vinyl.create(album_name:"Enema of the State", artist_name:"Blink 182")
Vinyl.create(album_name:"Nirvana Hits", artist_name:"Nirvana")
Vinyl.create(album_name:"UNplugged in New York", artist_name:"Nirvana")
Vinyl.create(album_name:"Surfer Rosa", artist_name:"Pixies")
Vinyl.create(album_name:"Yeezus", artist_name:"Kanye West")
Vinyl.create(album_name:"My Beautiful Dark Twisted Fantasy", artist_name:"Kanye West")
Vinyl.create(album_name:"Ye", artist_name:"Kanye West")
Vinyl.create(album_name:"Kids See Ghost", artist_name:"Kanye West")
Vinyl.create(album_name:"Life of Pablo", artist_name:"Kanye West")
Vinyl.create(album_name:"Welcome to Forever", artist_name:"Logic")
Vinyl.create(album_name:"Heroes and Villains", artist_name:"Metro Boomin")
Vinyl.create(album_name:"Return of Saturn", artist_name:"No Doubt")
Vinyl.create(album_name:"Tragic Kingdom", artist_name:"No Doubt")
Vinyl.create(album_name:"The Life of Pi'erre 4", artist_name:"Pi'erre Bourne")
Vinyl.create(album_name:"The Life of Pi'erre 5", artist_name:"Pi'erre Bourne")
Vinyl.create(album_name:"Three Imaginary Boys", artist_name:"The Cure")
Vinyl.create(album_name:"Damn", artist_name:"Kendrick Lamar")
Vinyl.create(album_name:"The Woo", artist_name:"Pop Smoke")
Vinyl.create(album_name:"Luv is Rage 2", artist_name:"Lil Uzi Vert")
Vinyl.create(album_name:"Ohms", artist_name:"Deftones")
Vinyl.create(album_name:"Me and your Mama", artist_name:"Childish Gambino")
Vinyl.create(album_name:"Diary 001", artist_name:"Clairo")
Vinyl.create(album_name:"No Stylist", artist_name:"Destroy Lonely")
Vinyl.create(album_name:"Superclean", artist_name:"The Marias")